name: Publish NPM Package

on:
  push:
    tags:
      - v**

jobs:
  publish-npm:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: prepare npm auth token
        run: echo  "\n//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: npm ci
      - run: npm run build
      - name: publish to npm
        working-directory: ./dist
        run: npm publish
